"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "ar" | "en"
type Theme = "light" | "dark"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  theme: Theme
  setTheme: (theme: Theme) => void
  toggleTheme: () => void
  t: (key: string) => string
}

const translations = {
  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.about": "من نحن",
    "nav.howItWorks": "كيف يعمل",
    "nav.technologies": "التقنيات",
    "nav.login": "تسجيل الدخول",
    "nav.dashboard": "لوحة التحكم",
    "nav.contact": "تواصل معنا",
    "nav.video": "شاهد الفيديو",

    // Home Page
    "home.hero.title": "مدقق - نظام كشف الاحتيال المالي",
    "home.hero.subtitle":
      "نظام ذكاء اصطناعي متطور لرصد واكتشاف الاحتيال المالي في خدمات وزارة الموارد البشرية والتنمية الاجتماعية",
    "home.hero.cta": "دخول النظام",
    "home.hero.watchVideo": "شاهد كيف يعمل",
    "home.features.title": "مميزات النظام",
    "home.features.subtitle": "نظام متكامل لكشف الاحتيال المالي والتحايل على نطاقات العمل",
    "home.features.ai.title": "ذكاء اصطناعي متقدم",
    "home.features.ai.desc": "خوارزميات تعلم آلي لتحليل أنماط الاحتيال والكشف المبكر عن المخالفات",
    "home.features.realtime.title": "مراقبة فورية",
    "home.features.realtime.desc": "رصد مستمر للمعاملات والخدمات لضمان اكتشاف الاحتيال فور حدوثه",
    "home.features.reports.title": "تقارير تفصيلية",
    "home.features.reports.desc": "تقارير شاملة وتوصيات دقيقة للحد من المخالفات وتعزيز النزاهة",
    "home.features.security.title": "أمان عالي المستوى",
    "home.features.security.desc": "حماية متقدمة للبيانات مع ضمان السرية والخصوصية التامة",
    "home.stats.analyzed": "معاملة محللة",
    "home.stats.accuracy": "دقة الكشف",
    "home.stats.organizations": "جهة حكومية",
    "home.stats.responseTime": "زمن الاستجابة",
    "home.badge.platform": "منصة مدقق الحكومية",
    "home.dashboard.title": "لوحة تحكم متطورة",
    "home.dashboard.subtitle": "واجهة شاملة لإدارة ومراقبة عمليات كشف الاحتيال",
    "home.dashboard.explore": "استكشاف لوحة التحكم",
    "home.dashboard.overview.title": "نظرة عامة شاملة",
    "home.dashboard.overview.desc": "عرض كامل للبيانات والإحصائيات الرئيسية في مكان واحد",
    "home.dashboard.analytics.title": "تحليلات متقدمة",
    "home.dashboard.analytics.desc": "رؤى عميقة وتحليل للاتجاهات والأنماط المالية",
    "home.dashboard.monitoring.title": "مراقبة مستمرة",
    "home.dashboard.monitoring.desc": "متابعة المعاملات والأنشطة في الوقت الفعلي",
    "home.dashboard.reports.title": "تقارير مخصصة",
    "home.dashboard.reports.desc": "إنشاء وتصدير تقارير مفصلة حسب الحاجة",

    // About Page
    "about.title": "من نحن",
    "about.subtitle": "نحن فريق متخصص في تطوير حلول الذكاء الاصطناعي لحماية الأموال العامة",
    "about.badge.platform": "منصة حكومية متطورة",
    "about.description":
      "مدقق هو منصة ذكاء اصطناعي حكومية متطورة تهدف إلى كشف الاحتيال المالي وحماية الأموال العامة. تستخدم المنصة أحدث تقنيات التعلم الآلي والذكاء الاصطناعي لتحليل البيانات المالية وكشف الأنماط المشبوهة بدقة عالية.",
    "about.vision.title": "رؤيتنا",
    "about.vision.desc": "أن نكون المنصة الرائدة في حماية الأموال العامة وتعزيز النزاهة المالية في الجهات الحكومية",
    "about.mission.title": "مهمتنا",
    "about.mission.desc":
      "توفير حلول ذكية ومتطورة لكشف الاحتيال المالي وحماية الموارد العامة من خلال تقنيات الذكاء الاصطناعي",
    "about.values.title": "قيمنا",
    "about.values.desc": "النزاهة والشفافية والابتكار والتميز في خدمة المصلحة العامة",
    "about.coreValues": "قيمنا الأساسية",
    "about.values.integrity.title": "النزاهة",
    "about.values.integrity.desc": "الالتزام بأعلى معايير النزاهة والشفافية في جميع عملياتنا",
    "about.values.innovation.title": "الابتكار",
    "about.values.innovation.desc": "استخدام أحدث التقنيات والحلول المبتكرة لتحقيق أفضل النتائج",
    "about.values.excellence.title": "التميز",
    "about.values.excellence.desc": "السعي المستمر لتحقيق التميز في جودة الخدمات المقدمة",
    "about.values.collaboration.title": "التعاون",
    "about.values.collaboration.desc": "العمل بروح الفريق والتعاون مع جميع الجهات المعنية",
    "about.platformCapabilities": "قدرات المنصة",
    "about.capabilities.instantProcessing.title": "معالجة فورية",
    "about.capabilities.instantProcessing.desc": "معالجة البيانات وتحليلها في الوقت الفعلي",
    "about.capabilities.instantProcessing.stat": "< 1 ثانية",
    "about.capabilities.advancedSecurity.title": "أمان متقدم",
    "about.capabilities.advancedSecurity.desc": "حماية عالية المستوى للبيانات الحساسة",
    "about.capabilities.advancedSecurity.stat": "256-bit",
    "about.capabilities.comprehensiveCoverage.title": "تغطية شاملة",
    "about.capabilities.comprehensiveCoverage.desc": "مراقبة جميع القطاعات الحكومية",
    "about.capabilities.comprehensiveCoverage.stat": "24/7",
    "about.capabilities.highAccuracy.title": "دقة عالية",
    "about.capabilities.highAccuracy.desc": "دقة في كشف الاحتيال والأنماط المشبوهة",
    "about.capabilities.highAccuracy.stat": "99.5%",

    // How It Works
    "howItWorks.title": "كيف يعمل مدقق",
    "howItWorks.subtitle": "تعرف على آلية عمل منصة مدقق لكشف الاحتيال المالي",
    "howItWorks.badge.system": "نظام متطور",
    "howItWorks.step1.title": "جمع البيانات",
    "howItWorks.step1.desc": "جمع وتحليل البيانات المالية من مصادر متعددة بشكل آمن ومشفر",
    "howItWorks.step2.title": "التحليل الذكي",
    "howItWorks.step2.desc": "استخدام خوارزميات الذكاء الاصطناعي لتحليل البيانات وكشف الأنماط المشبوهة",
    "howItWorks.step3.title": "كشف المخاطر",
    "howItWorks.step3.desc": "تحديد وتصنيف المخاطر والحالات المشبوهة بدقة عالية",
    "howItWorks.step4.title": "التقارير والإجراءات",
    "howItWorks.step4.desc": "إنشاء تقارير مفصلة واتخاذ الإجراءات اللازمة لحماية الأموال",
    "howItWorks.step.phase": "المرحلة",
    "howItWorks.step.details":
      "تجميع البيانات من مصادر متعددة,تشفير وحماية البيانات,التحقق من صحة البيانات,تنظيف وتحضير البيانات,تطبيق خوارزميات التعلم الآلي,تحليل الأنماط والسلوكيات,كشف الشذوذ والانحرافات,التحقق من النتائج,تحديد مستوى المخاطر,تصنيف الحالات المشبوهة,إرسال التنبيهات الفورية,توثيق النتائج,إنشاء التقارير التفصيلية,تقديم التوصيات,متابعة الإجراءات,تحديث قواعد البيانات",
    "howItWorks.features.title": "مميزات النظام",
    "howItWorks.features.speed.title": "سرعة المعالجة",
    "howItWorks.features.speed.desc": "معالجة البيانات في أقل من ثانية واحدة",
    "howItWorks.features.security.title": "الأمان والحماية",
    "howItWorks.features.security.desc": "تشفير متقدم وحماية عالية للبيانات",
    "howItWorks.features.monitoring.title": "المراقبة المستمرة",
    "howItWorks.features.monitoring.desc": "مراقبة على مدار الساعة طوال أيام الأسبوع",
    "howItWorks.features.reports.title": "التقارير الذكية",
    "howItWorks.features.reports.desc": "تقارير تفصيلية مع رؤى قابلة للتنفيذ",
    "howItWorks.cta.title": "جاهز لبدء الحماية؟",
    "howItWorks.cta.subtitle": "ابدأ في استخدام مدقق اليوم لحماية مؤسستك من الاحتيال المالي",
    "howItWorks.cta.start": "ابدأ الآن",
    "howItWorks.cta.contact": "تواصل معنا",

    // Technologies
    "tech.title": "التقنيات المستخدمة",
    "tech.subtitle": "نستخدم أحدث التقنيات والأدوات لضمان أفضل أداء وأمان",
    "tech.badge.advanced": "تقنيات متقدمة",
    "tech.categories.ai": "الذكاء الاصطناعي",
    "tech.categories.database": "قواعد البيانات",
    "tech.categories.security": "الأمان والحماية",
    "tech.categories.frontend": "واجهة المستخدم",
    "tech.categories.cloud": "الحوسبة السحابية",
    "tech.categories.api": "واجهات البرمجة",
    "tech.architecture": "هندسة النظام",
    "tech.architecture.frontend": "الواجهة الأمامية",
    "tech.architecture.frontend.desc": "واجهة مستخدم تفاعلية وسريعة الاستجابة",
    "tech.architecture.backend": "الخادم الخلفي",
    "tech.architecture.backend.desc": "خوادم قوية وموثوقة لمعالجة البيانات",
    "tech.architecture.ai": "محرك الذكاء الاصطناعي",
    "tech.architecture.ai.desc": "خوارزميات متطورة لكشف الاحتيال",
    "tech.integrations": "التكاملات",
    "tech.integrations.hrsd": "الأنظمة الحكومية",
    "tech.integrations.hrsd.desc": "تكامل مع أنظمة إدارة الموارد البشرية",
    "tech.integrations.absher": "الأنظمة الخارجية",
    "tech.integrations.absher.desc": "ربط مع الخدمات الخارجية",
    "tech.integrations.sadad": "أنظمة الدفع",
    "tech.integrations.sadad.desc": "تكامل مع أنظمة المدفوعات",
    "tech.integrations.qiwa": "منصات العمل",
    "tech.integrations.qiwa.desc": "ربط مع منصات سوق العمل",
    "tech.integrations.status": "متصل",
    "tech.integrations.active": "نشط",
    "tech.performance": "مؤشرات الأداء",
    "tech.performance.uptime": "وقت التشغيل",
    "tech.performance.encryption": "التشفير",
    "tech.performance.transactions": "المعاملات اليومية",
    "tech.performance.support": "الدعم التقني",

    // Video Page
    "video.title": "شاهد كيف يعمل مدقق",
    "video.subtitle": "فيديو تعريفي شامل يوضح كيفية استخدام منصة مدقق لكشف الاحتيال المالي",
    "video.badge.explanatory": "فيديو تعريفي",
    "video.backHome": "العودة للرئيسية",
    "video.coming": "قريباً",
    "video.description": "فيديو تعريفي شامل سيكون متاحاً قريباً",
    "video.download": "تحميل",
    "video.share": "مشاركة",
    "video.durationLabel": "15 دقيقة",
    "video.features.title": "مميزات الفيديو",
    "video.features.interactive.title": "تفاعلي",
    "video.features.interactive.description": "فيديو تفاعلي مع إمكانية التنقل بين الأقسام",
    "video.features.duration.title": "مدة مناسبة",
    "video.features.duration.description": "15 دقيقة من المحتوى المفيد والمركز",
    "video.features.accessibility.title": "سهولة الوصول",
    "video.features.accessibility.description": "متاح بعدة لغات مع ترجمة نصية",
    "video.features.quality.title": "جودة عالية",
    "video.features.quality.description": "فيديو بجودة 4K مع صوت واضح",
    "video.topics.title": "محتويات الفيديو",
    "video.topics.description": "المواضيع التي يغطيها الفيديو التعريفي",
    "video.topics.introduction": "مقدمة عن منصة مدقق وأهدافها",
    "video.topics.login": "كيفية تسجيل الدخول والبدء",
    "video.topics.dashboard": "جولة في لوحة التحكم الرئيسية",
    "video.topics.analysis": "كيفية تحليل الحالات المشبوهة",
    "video.topics.reports": "إنشاء وتصدير التقارير",
    "video.topics.security": "ميزات الأمان والحماية",
    "video.topics.integration": "التكامل مع الأنظمة الأخرى",
    "video.topics.tips": "نصائح وأفضل الممارسات",
    "video.quickStart.title": "بدء سريع",
    "video.quickStart.description": "ابدأ في استخدام المنصة الآن",
    "video.quickStart.login": "تسجيل الدخول",
    "video.quickStart.explore": "استكشاف المنصة",
    "video.helpSupport.title": "المساعدة والدعم",
    "video.helpSupport.description": "احصل على المساعدة التي تحتاجها",
    "video.helpSupport.contact": "تواصل معنا",
    "video.helpSupport.howItWorks": "كيف يعمل",
    "video.statistics.views": "مشاهدة متوقعة",

    // Contact Page
    "contact.title": "تواصل معنا",
    "contact.subtitle": "نحن هنا لمساعدتك، تواصل معنا في أي وقت",
    "contact.badge.contact": "تواصل",
    "contact.form.title": "أرسل رسالة",
    "contact.form.subtitle": "املأ النموذج وسنتواصل معك قريباً",
    "contact.name": "الاسم الكامل",
    "contact.email": "البريد الإلكتروني",
    "contact.subject": "الموضوع",
    "contact.message": "الرسالة",
    "contact.send": "إرسال الرسالة",
    "contact.sending": "جاري الإرسال...",
    "contact.success": "تم إرسال رسالتك بنجاح! سنتواصل معك قريباً.",
    "contact.validation.nameRequired": "الاسم مطلوب",
    "contact.validation.emailRequired": "البريد الإلكتروني مطلوب",
    "contact.validation.emailInvalid": "البريد الإلكتروني غير صحيح",
    "contact.validation.subjectRequired": "الموضوع مطلوب",
    "contact.validation.messageRequired": "الرسالة مطلوبة",
    "contact.info.title": "معلومات التواصل",
    "contact.info.subtitle": "يمكنك التواصل معنا عبر الطرق التالية",
    "contact.info.email.title": "البريد الإلكتروني",
    "contact.info.email.desc": "راسلنا في أي وقت",
    "contact.info.phone.title": "الهاتف",
    "contact.info.phone.desc": "اتصل بنا للدعم الفوري",
    "contact.info.address.title": "العنوان",
    "contact.info.address.desc": "موقعنا الرئيسي",
    "contact.info.hours.title": "ساعات العمل",
    "contact.info.hours.value": "الأحد - الخميس: 8:00 - 17:00",
    "contact.info.hours.desc": "نحن متاحون للمساعدة",
    "contact.faq.title": "الأسئلة الشائعة",
    "contact.faq.subtitle": "إجابات على أكثر الأسئلة شيوعاً",
    "contact.faq.q1": "كيف يمكنني الحصول على حساب في المنصة؟",
    "contact.faq.a1": "يمكنك التواصل معنا لإنشاء حساب جديد للجهة التي تعمل بها.",
    "contact.faq.q2": "هل البيانات آمنة في المنصة؟",
    "contact.faq.a2": "نعم، نستخدم أعلى معايير الأمان والتشفير لحماية جميع البيانات.",
    "contact.faq.q3": "كم تستغرق عملية تحليل البيانات؟",
    "contact.faq.a3": "تتم معالجة البيانات وتحليلها في الوقت الفعلي خلال أقل من ثانية واحدة.",
    "contact.faq.q4": "هل يمكن تخصيص التقارير؟",
    "contact.faq.a4": "نعم، يمكنك إنشاء تقارير مخصصة حسب احتياجات جهتك.",
    "contact.social.title": "وسائل التواصل الاجتماعي",
    "contact.social.desc": "تابعنا على وسائل التواصل الاجتماعي",
    "contact.emergency.title": "حالات الطوارئ",
    "contact.emergency.desc": "للحالات العاجلة والطوارئ الأمنية",
    "contact.emergency.call": "اتصال طارئ",
    "contact.emergency.email": "بريد طارئ",
    "contact.noAccount": "ليس لديك حساب؟",
    "contact.createAccount": "تواصل معنا لإنشاء حساب",

    // Login
    "login.title": "تسجيل الدخول",
    "login.subtitle": "ادخل إلى حسابك للوصول إلى لوحة التحكم",
    "login.email": "البريد الإلكتروني",
    "login.password": "كلمة المرور",
    "login.submit": "دخول",
    "login.rememberMe": "تذكرني",
    "login.loggingIn": "جاري تسجيل الدخول...",
    "login.demoCredentials": "بيانات تجريبية",
    "login.createAccount": "تواصل معنا لإنشاء حساب",

    // Dashboard
    "dashboard.title": "لوحة التحكم",
    "dashboard.welcome": "مرحباً بك في مدقق",
    "dashboard.totalCases": "إجمالي الحالات",
    "dashboard.suspiciousCases": "الحالات المشبوهة",
    "dashboard.resolvedCases": "الحالات المحلولة",
    "dashboard.riskLevel": "مستوى المخاطر",
    "dashboard.recentCases": "الحالات الأخيرة",
    "dashboard.viewDetails": "عرض التفاصيل",
    "dashboard.analyzeCase": "تحليل حالة جديدة",
    "dashboard.lastUpdate": "آخر تحديث: منذ 5 دقائق",
    "dashboard.systemActive": "النظام نشط",
    "dashboard.exportReport": "تصدير التقرير",
    "dashboard.quickActions": "إجراءات سريعة",
    "dashboard.riskAnalysis": "تحليل المخاطر",
    "dashboard.recentActivity": "النشاط الأخير",
    "dashboard.systemStatus": "حالة النظام",
    "dashboard.uptime": "وقت التشغيل",
    "dashboard.lastCheck": "آخر فحص",
    "dashboard.allSystemsOperational": "جميع الأنظمة تعمل بشكل طبيعي",
    "dashboard.searchCases": "البحث في الحالات...",
    "dashboard.allCases": "جميع الحالات",
    "dashboard.underInvestigation": "قيد التحقيق",
    "dashboard.resolved": "تم الحل",
    "dashboard.underReview": "مراجعة",
    "dashboard.progress": "التقدم",
    "dashboard.investigator": "المحقق",
    "dashboard.expectedCompletion": "الإنجاز المتوقع",
    "dashboard.riskDistribution": "توزيع الحالات حسب مستوى المخاطر",
    "dashboard.highRisk": "مخاطر عالية",
    "dashboard.mediumRisk": "مخاطر متوسطة",
    "dashboard.lowRisk": "مخاطر منخفضة",
    "dashboard.cases": "حالة",
    "dashboard.systemActivities": "آخر الأنشطة في النظام",
    "dashboard.newCase": "تحليل حالة جديدة",
    "dashboard.newCaseDesc": "ابدأ تحليل حالة احتيال جديدة",
    "dashboard.createReport": "إنشاء تقرير",
    "dashboard.createReportDesc": "أنشئ تقرير مخصص للإدارة",
    "dashboard.scheduleReview": "جدولة مراجعة",
    "dashboard.scheduleReviewDesc": "حدد موعد لمراجعة الحالات",
    "dashboard.systemSettings": "إعدادات النظام",
    "dashboard.systemSettingsDesc": "تخصيص إعدادات المراقبة",

    // Theme
    "theme.light": "الوضع النهاري",
    "theme.dark": "الوضع الليلي",
    "theme.toggle": "تبديل النمط",

    // Footer
    "footer.rights": "© 2024 وزارة الموارد البشرية والتنمية الاجتماعية. جميع الحقوق محفوظة.",
    "footer.company": "وزارة الموارد البشرية والتنمية الاجتماعية",
    "footer.location": "المملكة العربية السعودية",
    "footer.quickLinks": "روابط سريعة",
    "footer.contactInfo": "معلومات التواصل",
    "footer.followUs": "تابعنا",
    "footer.address": "الرياض، المملكة العربية السعودية",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.howItWorks": "How It Works",
    "nav.technologies": "Technologies",
    "nav.login": "Login",
    "nav.dashboard": "Dashboard",
    "nav.contact": "Contact",
    "nav.video": "Watch Video",

    // Home Page
    "home.hero.title": "Modaqqeq - Financial Fraud Detection System",
    "home.hero.subtitle":
      "Advanced AI system for monitoring and detecting financial fraud in Ministry of Human Resources and Social Development services",
    "home.hero.cta": "Access System",
    "home.hero.watchVideo": "Watch How It Works",
    "home.features.title": "System Features",
    "home.features.subtitle": "Integrated system for detecting financial fraud and work permit violations",
    "home.features.ai.title": "Advanced AI",
    "home.features.ai.desc": "Machine learning algorithms to analyze fraud patterns and early detection of violations",
    "home.features.realtime.title": "Real-time Monitoring",
    "home.features.realtime.desc":
      "Continuous monitoring of transactions and services to ensure immediate fraud detection",
    "home.features.reports.title": "Detailed Reports",
    "home.features.reports.desc":
      "Comprehensive reports and accurate recommendations to reduce violations and enhance integrity",
    "home.features.security.title": "High-Level Security",
    "home.features.security.desc": "Advanced data protection with complete confidentiality and privacy assurance",
    "home.stats.analyzed": "Transactions Analyzed",
    "home.stats.accuracy": "Detection Accuracy",
    "home.stats.organizations": "Government Entities",
    "home.stats.responseTime": "Response Time",
    "home.badge.platform": "Modaqqeq Government Platform",
    "home.dashboard.title": "Advanced Dashboard",
    "home.dashboard.subtitle": "Comprehensive interface for managing and monitoring fraud detection operations",
    "home.dashboard.explore": "Explore Dashboard",
    "home.dashboard.overview.title": "Comprehensive Overview",
    "home.dashboard.overview.desc": "Complete view of key data and statistics in one place",
    "home.dashboard.analytics.title": "Advanced Analytics",
    "home.dashboard.analytics.desc": "Deep insights and analysis of financial trends and patterns",
    "home.dashboard.monitoring.title": "Continuous Monitoring",
    "home.dashboard.monitoring.desc": "Real-time transaction and activity tracking",
    "home.dashboard.reports.title": "Custom Reports",
    "home.dashboard.reports.desc": "Create and export detailed reports as needed",

    // About Page
    "about.title": "About Us",
    "about.subtitle": "We are a specialized team in developing AI solutions to protect public funds",
    "about.badge.platform": "Advanced Government Platform",
    "about.description":
      "Modaqqeq is an advanced government AI platform aimed at detecting financial fraud and protecting public funds. The platform uses the latest machine learning and artificial intelligence technologies to analyze financial data and detect suspicious patterns with high accuracy.",
    "about.vision.title": "Our Vision",
    "about.vision.desc":
      "To be the leading platform in protecting public funds and enhancing financial integrity in government entities",
    "about.mission.title": "Our Mission",
    "about.mission.desc":
      "Providing smart and advanced solutions to detect financial fraud and protect public resources through artificial intelligence technologies",
    "about.values.title": "Our Values",
    "about.values.desc": "Integrity, transparency, innovation, and excellence in serving the public interest",
    "about.coreValues": "Core Values",
    "about.values.integrity.title": "Integrity",
    "about.values.integrity.desc":
      "Commitment to the highest standards of integrity and transparency in all our operations",
    "about.values.innovation.title": "Innovation",
    "about.values.innovation.desc":
      "Using the latest technologies and innovative solutions to achieve the best results",
    "about.values.excellence.title": "Excellence",
    "about.values.excellence.desc": "Continuous pursuit of excellence in the quality of services provided",
    "about.values.collaboration.title": "Collaboration",
    "about.values.collaboration.desc": "Working in team spirit and cooperation with all stakeholders",
    "about.platformCapabilities": "Platform Capabilities",
    "about.capabilities.instantProcessing.title": "Instant Processing",
    "about.capabilities.instantProcessing.desc": "Real-time data processing and analysis",
    "about.capabilities.instantProcessing.stat": "< 1 second",
    "about.capabilities.advancedSecurity.title": "Advanced Security",
    "about.capabilities.advancedSecurity.desc": "High-level protection for sensitive data",
    "about.capabilities.advancedSecurity.stat": "256-bit",
    "about.capabilities.comprehensiveCoverage.title": "Comprehensive Coverage",
    "about.capabilities.comprehensiveCoverage.desc": "Monitoring all government sectors",
    "about.capabilities.comprehensiveCoverage.stat": "24/7",
    "about.capabilities.highAccuracy.title": "High Accuracy",
    "about.capabilities.highAccuracy.desc": "Accuracy in fraud detection and suspicious patterns",
    "about.capabilities.highAccuracy.stat": "99.5%",

    // How It Works
    "howItWorks.title": "How Modaqqeq Works",
    "howItWorks.subtitle": "Learn about the mechanism of Modaqqeq platform for financial fraud detection",
    "howItWorks.badge.system": "Advanced System",
    "howItWorks.step1.title": "Data Collection",
    "howItWorks.step1.desc": "Collecting and analyzing financial data from multiple sources securely and encrypted",
    "howItWorks.step2.title": "Smart Analysis",
    "howItWorks.step2.desc": "Using AI algorithms to analyze data and detect suspicious patterns",
    "howItWorks.step3.title": "Risk Detection",
    "howItWorks.step3.desc": "Identifying and classifying risks and suspicious cases with high accuracy",
    "howItWorks.step4.title": "Reports and Actions",
    "howItWorks.step4.desc": "Creating detailed reports and taking necessary actions to protect funds",
    "howItWorks.step.phase": "Phase",
    "howItWorks.step.details":
      "Collecting data from multiple sources,Encrypting and protecting data,Verifying data integrity,Cleaning and preparing data,Applying machine learning algorithms,Analyzing patterns and behaviors,Detecting anomalies and deviations,Verifying results,Determining risk level,Classifying suspicious cases,Sending instant alerts,Documenting results,Creating detailed reports,Providing recommendations,Following up on actions,Updating databases",
    "howItWorks.features.title": "System Features",
    "howItWorks.features.speed.title": "Processing Speed",
    "howItWorks.features.speed.desc": "Data processing in less than one second",
    "howItWorks.features.security.title": "Security and Protection",
    "howItWorks.features.security.desc": "Advanced encryption and high data protection",
    "howItWorks.features.monitoring.title": "Continuous Monitoring",
    "howItWorks.features.monitoring.desc": "24/7 monitoring throughout the week",
    "howItWorks.features.reports.title": "Smart Reports",
    "howItWorks.features.reports.desc": "Detailed reports with actionable insights",
    "howItWorks.cta.title": "Ready to Start Protection?",
    "howItWorks.cta.subtitle": "Start using Modaqqeq today to protect your organization from financial fraud",
    "howItWorks.cta.start": "Get Started",
    "howItWorks.cta.contact": "Contact Us",

    // Technologies
    "tech.title": "Technologies Used",
    "tech.subtitle": "We use the latest technologies and tools to ensure the best performance and security",
    "tech.badge.advanced": "Advanced Technologies",
    "tech.categories.ai": "Artificial Intelligence",
    "tech.categories.database": "Databases",
    "tech.categories.security": "Security & Protection",
    "tech.categories.frontend": "User Interface",
    "tech.categories.cloud": "Cloud Computing",
    "tech.categories.api": "APIs",
    "tech.architecture": "System Architecture",
    "tech.architecture.frontend": "Frontend",
    "tech.architecture.frontend.desc": "Interactive and responsive user interface",
    "tech.architecture.backend": "Backend",
    "tech.architecture.backend.desc": "Powerful and reliable servers for data processing",
    "tech.architecture.ai": "AI Engine",
    "tech.architecture.ai.desc": "Advanced algorithms for fraud detection",
    "tech.integrations": "Integrations",
    "tech.integrations.hrsd": "Government Systems",
    "tech.integrations.hrsd.desc": "Integration with HR management systems",
    "tech.integrations.absher": "External Systems",
    "tech.integrations.absher.desc": "Connection with external services",
    "tech.integrations.sadad": "Payment Systems",
    "tech.integrations.sadad.desc": "Integration with payment systems",
    "tech.integrations.qiwa": "Work Platforms",
    "tech.integrations.qiwa.desc": "Connection with labor market platforms",
    "tech.integrations.status": "Connected",
    "tech.integrations.active": "Active",
    "tech.performance": "Performance Metrics",
    "tech.performance.uptime": "Uptime",
    "tech.performance.encryption": "Encryption",
    "tech.performance.transactions": "Daily Transactions",
    "tech.performance.support": "Technical Support",

    // Video Page
    "video.title": "Watch How Modaqqeq Works",
    "video.subtitle":
      "Comprehensive introductory video explaining how to use Modaqqeq platform for financial fraud detection",
    "video.badge.explanatory": "Explanatory Video",
    "video.backHome": "Back to Home",
    "video.coming": "Coming Soon",
    "video.description": "Comprehensive introductory video will be available soon",
    "video.download": "Download",
    "video.share": "Share",
    "video.durationLabel": "15 minutes",
    "video.features.title": "Video Features",
    "video.features.interactive.title": "Interactive",
    "video.features.interactive.description": "Interactive video with navigation between sections",
    "video.features.duration.title": "Appropriate Duration",
    "video.features.duration.description": "15 minutes of useful and focused content",
    "video.features.accessibility.title": "Accessibility",
    "video.features.accessibility.description": "Available in multiple languages with subtitles",
    "video.features.quality.title": "High Quality",
    "video.features.quality.description": "4K video with clear audio",
    "video.topics.title": "Video Contents",
    "video.topics.description": "Topics covered in the introductory video",
    "video.topics.introduction": "Introduction to Modaqqeq platform and its objectives",
    "video.topics.login": "How to login and get started",
    "video.topics.dashboard": "Tour of the main dashboard",
    "video.topics.analysis": "How to analyze suspicious cases",
    "video.topics.reports": "Creating and exporting reports",
    "video.topics.security": "Security and protection features",
    "video.topics.integration": "Integration with other systems",
    "video.topics.tips": "Tips and best practices",
    "video.quickStart.title": "Quick Start",
    "video.quickStart.description": "Start using the platform now",
    "video.quickStart.login": "Login",
    "video.quickStart.explore": "Explore Platform",
    "video.helpSupport.title": "Help & Support",
    "video.helpSupport.description": "Get the help you need",
    "video.helpSupport.contact": "Contact Us",
    "video.helpSupport.howItWorks": "How It Works",
    "video.statistics.views": "Expected Views",

    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "We are here to help you, contact us anytime",
    "contact.badge.contact": "Contact",
    "contact.form.title": "Send Message",
    "contact.form.subtitle": "Fill out the form and we will contact you soon",
    "contact.name": "Full Name",
    "contact.email": "Email",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.success": "Your message has been sent successfully! We will contact you soon.",
    "contact.validation.nameRequired": "Name is required",
    "contact.validation.emailRequired": "Email is required",
    "contact.validation.emailInvalid": "Invalid email",
    "contact.validation.subjectRequired": "Subject is required",
    "contact.validation.messageRequired": "Message is required",
    "contact.info.title": "Contact Information",
    "contact.info.subtitle": "You can contact us through the following methods",
    "contact.info.email.title": "Email",
    "contact.info.email.desc": "Email us anytime",
    "contact.info.phone.title": "Phone",
    "contact.info.phone.desc": "Call us for immediate support",
    "contact.info.address.title": "Address",
    "contact.info.address.desc": "Our main location",
    "contact.info.hours.title": "Working Hours",
    "contact.info.hours.value": "Sunday - Thursday: 8:00 - 17:00",
    "contact.info.hours.desc": "We are available to help",
    "contact.faq.title": "Frequently Asked Questions",
    "contact.faq.subtitle": "Answers to the most common questions",
    "contact.faq.q1": "How can I get an account on the platform?",
    "contact.faq.a1": "You can contact us to create a new account for the entity you work for.",
    "contact.faq.q2": "Is data safe on the platform?",
    "contact.faq.a2": "Yes, we use the highest security and encryption standards to protect all data.",
    "contact.faq.q3": "How long does data analysis take?",
    "contact.faq.a3": "Data is processed and analyzed in real-time within less than one second.",
    "contact.faq.q4": "Can reports be customized?",
    "contact.faq.a4": "Yes, you can create custom reports according to your entity's needs.",
    "contact.social.title": "Social Media",
    "contact.social.desc": "Follow us on social media",
    "contact.emergency.title": "Emergency Cases",
    "contact.emergency.desc": "For urgent cases and security emergencies",
    "contact.emergency.call": "Emergency Call",
    "contact.emergency.email": "Emergency Email",
    "contact.noAccount": "Don't have an account?",
    "contact.createAccount": "Contact us to create an account",

    // Login
    "login.title": "Login",
    "login.subtitle": "Enter your account to access the dashboard",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit": "Login",
    "login.rememberMe": "Remember Me",
    "login.loggingIn": "Logging in...",
    "login.demoCredentials": "Demo Credentials",
    "login.createAccount": "Contact us to create an account",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome to Modaqqeq",
    "dashboard.totalCases": "Total Cases",
    "dashboard.suspiciousCases": "Suspicious Cases",
    "dashboard.resolvedCases": "Resolved Cases",
    "dashboard.riskLevel": "Risk Level",
    "dashboard.recentCases": "Recent Cases",
    "dashboard.viewDetails": "View Details",
    "dashboard.analyzeCase": "Analyze New Case",
    "dashboard.lastUpdate": "Last update: 5 minutes ago",
    "dashboard.systemActive": "System active",
    "dashboard.exportReport": "Export Report",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.riskAnalysis": "Risk Analysis",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.systemStatus": "System Status",
    "dashboard.uptime": "Uptime",
    "dashboard.lastCheck": "Last check",
    "dashboard.allSystemsOperational": "All systems operating normally",
    "dashboard.searchCases": "Search cases...",
    "dashboard.allCases": "All Cases",
    "dashboard.underInvestigation": "Under Investigation",
    "dashboard.resolved": "Resolved",
    "dashboard.underReview": "Under Review",
    "dashboard.progress": "Progress",
    "dashboard.investigator": "Investigator",
    "dashboard.expectedCompletion": "Expected completion",
    "dashboard.riskDistribution": "Case distribution by risk level",
    "dashboard.highRisk": "High Risk",
    "dashboard.mediumRisk": "Medium Risk",
    "dashboard.lowRisk": "Low Risk",
    "dashboard.cases": "cases",
    "dashboard.systemActivities": "Latest system activities",
    "dashboard.newCase": "Analyze New Case",
    "dashboard.newCaseDesc": "Start analyzing a new fraud case",
    "dashboard.createReport": "Create Report",
    "dashboard.createReportDesc": "Create a custom report for management",
    "dashboard.scheduleReview": "Schedule Review",
    "dashboard.scheduleReviewDesc": "Schedule a case review appointment",
    "dashboard.systemSettings": "System Settings",
    "dashboard.systemSettingsDesc": "Customize monitoring settings",

    // Theme
    "theme.light": "Light Mode",
    "theme.dark": "Dark Mode",
    "theme.toggle": "Toggle Theme",

    // Footer
    "footer.rights": "© 2024 Ministry of Human Resources and Social Development. All rights reserved.",
    "footer.company": "Ministry of Human Resources and Social Development",
    "footer.location": "Kingdom of Saudi Arabia",
    "footer.quickLinks": "Quick Links",
    "footer.contactInfo": "Contact Information",
    "footer.followUs": "Follow Us",
    "footer.address": "Riyadh, Kingdom of Saudi Arabia",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("ar")
  const [theme, setTheme] = useState<Theme>("light")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["ar"]] || key
  }

  const toggleTheme = () => {
    setTheme((prev) => (prev === "light" ? "dark" : "light"))
  }

  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr"
  }, [language])

  useEffect(() => {
    document.documentElement.classList.toggle("dark", theme === "dark")
  }, [theme])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, theme, setTheme, toggleTheme, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
